version: '3.8'
services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend
    container_name: osrm-wa
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    command: osrm-routed --algorithm mld /data/washington-latest.osrm
    restart: unless-stopped
